release: "latest"

docker: "true"
docker_nginx_container: "joomlatools_nginx"
docker_apache_container: "joomlatools_apache"
docker_nginx: true
docker_apache: true
mysql_host_alias: "db"
php_fpm: "joomlatools_php_fpm:9000"
config_www: "/Sites/"
smtphost: "mailhog"
mysqld_output: "/docker-entrypoint-initdb.d/"
disable-ssl: true

www_dir: "/var/www"

mysql_host: "127.0.0.1"
mysql_port: "3306"
mysql_login: "root:root"
target_db_prefix: "sites_"
mysql_driver: "mysqli"
#smtphost: "localhost"
#mysqld_output:"/var/www/"

http_port: "80"
#disable-ssl: false
ssl_cert: "/etc/apache2/ssl/server.crt"
ssl_key: "/etc/apache2/ssl/server.key"
ssl_port: "443"
#php_fpm: "unix:/opt/php/php-fpm.sock"